apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: amq-mqtt
  application: amq-mqtt
  namespace: amq-mqtt
spec:
  acceptors:
    - port: 61616
      expose: true
      name: all
      protocols: all
      anycastPrefix: jms.queue.
      verifyHost: false
    - name: mqtt
      protocols: mqtt
      port: 8883
      sslEnabled: true
      sslSecret: amq-mqtt-mqtt-secret
      verifyHost: false
      expose: true
  adminPassword: admin
  deploymentPlan:
    size: 1
    persistenceEnabled: true
    requireLogin: false
    messageMigration: false
    managementRBACEnabled: true
    journalType: nio
    jolokiaAgentEnabled: false
    image: placeholder
  console:
    expose: true
  adminUser: admin

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: console
  namespace: amq-mqtt
spec:
  to:
    kind: Service
    name: amq-mqtt-hdls-svc
    weight: 100
  port:
    targetPort: console-jolokia
  wildcardPolicy: None
